# Generated by Django 5.2.6 on 2025-09-18 04:40

from django.db import migrations


def create_initial_data(apps, schema_editor):
    # Получаем модели
    Status = apps.get_model('dds', 'Status')
    TransactionType = apps.get_model('dds', 'TransactionType')
    Category = apps.get_model('dds', 'Category')
    Subcategory = apps.get_model('dds', 'SubCategory')
    
    # Создаем статусы
    statuses = ['Бизнес', 'Личное', 'Налог']
    for status_name in statuses:
        Status.objects.get_or_create(name=status_name)
    
    # Создаем типы транзакций
    transaction_types = ['Пополнение', 'Списание']
    for type_name in transaction_types:
        TransactionType.objects.get_or_create(name=type_name)
    
    # Создаем категории для пополнения
    categories = {
        'Инфраструктура': ['VPS', 'Proxy'],
        'Маркетинг': ['Farpost', 'Avito']
    }
    for category_name in categories.keys():
        category, created = Category.objects.get_or_create(name=category_name)
        for subcategory_name in categories[category_name]:
            Subcategory.objects.get_or_create(category=category, name=subcategory_name)
    

def reverse_initial_data(apps, schema_editor):
    # При откате миграции удаляем все данные
    Status = apps.get_model('dds', 'Status')
    TransactionType = apps.get_model('dds', 'TransactionType')
    Category = apps.get_model('dds', 'Category')
    Subcategory = apps.get_model('dds', 'Subcategory')
    
    Subcategory.objects.all().delete()
    Category.objects.all().delete()
    TransactionType.objects.all().delete()
    Status.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
